name = "srptiq"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "69b4e7a7912d4d8c8ec59579beb182bc"
localConnectionString = "postgresql://neondb_owner:npg_RGfy1EBbnet9@ep-lively-tree-aqk1jpmi.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require"
